# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Devil's Trap
version: 1.0.20
email: info@thedevilstrap.com
description: > # this means to ignore newlines until "baseurl:"
  Lane, an ex-ember of a cult called the Exclusive Brethren, attempts to
  re-unite with his estranged family who ex-communicated him from the cult
  when he was 18 years old. On his journey of absolute horrific nostalgia
  through his own psyche, he meets other ex-members, infiltrates Brethren
  churches, wanders through barren suburban landscapes, and tries to
  confront his pain on a two-week long cross Canada and U.S. road trip. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thedevilstrap.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_page: thedevilstrap

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
